build: off
deploy: off

init:
  - appveyor DownloadFile https://ci.appveyor.com/api/projects/MSP-Greg/ruby-loco/artifacts/ruby_trunk.7z -FileName C:/ruby_trunk.7z
  - 7z x C:/ruby_trunk.7z -oC:/ruby_trunk

test_script:
  - set vers_cmd=call gem list
  - vers_test.cmd
  # main_run.cmd
