build: off
deploy: off

init:
  - appveyor DownloadFile https://ci.appveyor.com/api/projects/MSP-Greg/ruby-loco/artifacts/ruby_trunk.7z -FileName C:/ruby_trunk.7z
  - 7z x C:/ruby_trunk.7z -oC:/ruby_trunk

test_script:
  - set rb_file=is_07968_socket_send_0010.rb
  - echo   10 Characters Send
  - vers_test.cmd

  - set rb_file=is_07968_socket_print_0010.rb
  - echo   10 Characters Print
  - vers_test.cmd

  - set rb_file=is_07968_socket_send_2000.rb
  - echo 2000 Characters Send
  - vers_test.cmd

  - set rb_file=is_07968_socket_print_2000.rb
  - echo 2000 Characters Print
  - vers_test.cmd
