build: off
deploy: off

init:
  - appveyor DownloadFile https://ci.appveyor.com/api/projects/MSP-Greg/ruby-loco/artifacts/ruby_trunk.7z -FileName C:/ruby_trunk.7z
  - 7z x C:/ruby_trunk.7z -oC:/ruby_trunk

test_script:
  - set base_path=C:/Program Files/7-Zip;C:/Program Files/AppVeyor/BuildAgent;C:/Program Files/Git/cmd;C:/Program Files (x86)/GNU/GnuPG/pub;C:/Windows/system32;C:/Windows

  - set PATH=C:/Ruby193/bin;%base_path%      & ruby -v is_07968_socketsendtest.rb
  
  - set PATH=C:/ruby200-x64/bin;%base_path%  & ruby -v is_07968_socketsendtest.rb

  - set PATH=C:/ruby21-x64/bin;%base_path%   & ruby -v is_07968_socketsendtest.rb
  
  - set PATH=C:/ruby22-x64/bin;%base_path%   & ruby -v is_07968_socketsendtest.rb

  - set PATH=C:/ruby23-x64/bin;%base_path%   & ruby -v is_07968_socketsendtest.rb

  - set PATH=C:/ruby24-x64/bin;%base_path%   & ruby -v is_07968_socketsendtest.rb

  - set PATH=C:/ruby_trunk/bin;%base_path%   & ruby -v is_07968_socketsendtest.rb
